import type { Estudiante, Empresa, Admin, Vacante, Postulacion, Practica, NotificacionItem } from './types'

export const mockEstudiante: Estudiante = {
  id: 'est-001',
  nombre: 'Samuel Salcedo',
  email: 'samuel.salcedo@unihumboldt.edu.co',
  rol: 'estudiante',
  universidad: 'Universidad Alexander Von Humboldt',
  programa: 'Ingeniería de Software',
  semestre: 7,
  habilidades: ['React', 'Node.js', 'Python', 'SQL', 'Git'],
  disponibilidad: 'medio_tiempo',
  etapaCarrera: 'aplicando',
}

export const mockEmpresa: Empresa = {
  id: 'emp-001',
  nombre: 'Carlos Herrera',
  email: 'carlos.herrera@techcorp.com.co',
  rol: 'empresa',
  razonSocial: 'TechCorp Colombia S.A.S',
  sector: 'Tecnología',
  ciudad: 'Armenia',
  tamaño: 'mediana',
}

export const mockAdmin: Admin = {
  id: 'adm-001',
  nombre: 'María Fernanda López',
  email: 'mflopez@unihumboldt.edu.co',
  rol: 'admin',
  universidad: 'Universidad Alexander Von Humboldt',
  cargo: 'Coordinadora de Prácticas',
}

export const mockVacantes: Vacante[] = [
  {
    id: 'vac-001',
    titulo: 'Desarrollador Frontend React',
    empresa: 'TechCorp Colombia',
    empresaId: 'emp-001',
    sector: 'Tecnología',
    ciudad: 'Armenia',
    modalidad: 'hibrido',
    tipo: 'practica',
    salario: { min: 1200000, max: 1800000 },
    descripcion: 'Buscamos practicante de ingeniería de sistemas para unirse al equipo frontend.',
    requisitos: ['Cursando mínimo semestre 6', 'Disponibilidad 20 horas semanales'],
    habilidades: ['React', 'TypeScript', 'CSS', 'Git'],
    fechaPublicacion: '2026-04-28',
    fechaCierre: '2026-05-25',
    postulaciones: 14,
    compatibilidad: 92,
  },
  {
    id: 'vac-002',
    titulo: 'Analista de Datos Junior',
    empresa: 'Grupo Éxito',
    empresaId: 'emp-002',
    sector: 'Retail',
    ciudad: 'Medellín',
    modalidad: 'remoto',
    tipo: 'medio_tiempo',
    salario: { min: 1500000, max: 2000000 },
    descripcion: 'Posición para análisis de datos de ventas y comportamiento del consumidor.',
    requisitos: ['Conocimientos en Python o R', 'Manejo de Excel avanzado'],
    habilidades: ['Python', 'SQL', 'Power BI', 'Excel'],
    fechaPublicacion: '2026-05-01',
    fechaCierre: '2026-05-30',
    postulaciones: 8,
    compatibilidad: 78,
  },
  {
    id: 'vac-003',
    titulo: 'Desarrollador Backend Node.js',
    empresa: 'Bancolombia',
    empresaId: 'emp-003',
    sector: 'Finanzas',
    ciudad: 'Bogotá',
    modalidad: 'presencial',
    tipo: 'practica',
    salario: { min: 1600000, max: 2200000 },
    descripcion: 'Práctica en el área de desarrollo de APIs REST para servicios financieros.',
    requisitos: ['Semestre 7 o superior', 'Aval universitario'],
    habilidades: ['Node.js', 'Express', 'PostgreSQL', 'Docker'],
    fechaPublicacion: '2026-05-03',
    fechaCierre: '2026-06-01',
    postulaciones: 22,
    compatibilidad: 85,
  },
  {
    id: 'vac-004',
    titulo: 'QA Engineer Trainee',
    empresa: 'Pragma',
    empresaId: 'emp-004',
    sector: 'Tecnología',
    ciudad: 'Pereira',
    modalidad: 'hibrido',
    tipo: 'practica',
    salario: { min: 1100000, max: 1500000 },
    descripcion: 'Aprende testing manual y automatizado en proyectos reales con clientes internacionales.',
    requisitos: ['Inglés intermedio', 'Cursando últimos semestres'],
    habilidades: ['Testing', 'Selenium', 'Jira', 'Git'],
    fechaPublicacion: '2026-05-05',
    fechaCierre: '2026-05-28',
    postulaciones: 6,
    compatibilidad: 70,
  },
  {
    id: 'vac-005',
    titulo: 'Ingeniero Cloud AWS',
    empresa: 'Nequi',
    empresaId: 'emp-005',
    sector: 'Fintech',
    ciudad: 'Medellín',
    modalidad: 'remoto',
    tipo: 'tiempo_completo',
    salario: { min: 3000000, max: 4500000 },
    descripcion: 'Posición full-time para recién egresados con experiencia en AWS y DevOps.',
    requisitos: ['Título profesional', 'Certificación AWS Cloud Practitioner'],
    habilidades: ['AWS', 'Docker', 'Terraform', 'CI/CD'],
    fechaPublicacion: '2026-05-07',
    fechaCierre: '2026-06-07',
    postulaciones: 31,
    compatibilidad: 62,
  },
  {
    id: 'vac-006',
    titulo: 'Practicante Diseño UX/UI',
    empresa: 'Rappi',
    empresaId: 'emp-006',
    sector: 'Tecnología',
    ciudad: 'Bogotá',
    modalidad: 'hibrido',
    tipo: 'practica',
    salario: { min: 1300000, max: 1700000 },
    descripcion: 'Práctica en el equipo de diseño de producto, trabajando en la app con millones de usuarios.',
    requisitos: ['Portafolio requerido', 'Figma intermedio'],
    habilidades: ['Figma', 'Prototyping', 'User Research', 'Design Systems'],
    fechaPublicacion: '2026-05-09',
    fechaCierre: '2026-05-31',
    postulaciones: 18,
    compatibilidad: 55,
  },
]

export const mockPostulaciones: Postulacion[] = [
  {
    id: 'post-001',
    vacanteId: 'vac-003',
    vacantetitulo: 'Desarrollador Backend Node.js',
    empresa: 'Bancolombia',
    sector: 'Finanzas',
    fechaPostulacion: '2026-05-04',
    estado: 'entrevista',
    compatibilidad: 85,
    modalidad: 'presencial',
    proximoPaso: 'Entrevista técnica el 14 de mayo a las 10:00 am',
  },
  {
    id: 'post-002',
    vacanteId: 'vac-002',
    vacantetitulo: 'Analista de Datos Junior',
    empresa: 'Grupo Éxito',
    sector: 'Retail',
    fechaPostulacion: '2026-05-02',
    estado: 'en_revision',
    compatibilidad: 78,
    modalidad: 'remoto',
  },
  {
    id: 'post-003',
    vacanteId: 'vac-004',
    vacantetitulo: 'QA Engineer Trainee',
    empresa: 'Pragma',
    sector: 'Tecnología',
    fechaPostulacion: '2026-05-06',
    estado: 'postulado',
    compatibilidad: 70,
    modalidad: 'hibrido',
  },
  {
    id: 'post-004',
    vacanteId: 'vac-007',
    vacantetitulo: 'Desarrollador Mobile Flutter',
    empresa: 'Celsia',
    sector: 'Energía',
    fechaPostulacion: '2026-04-20',
    estado: 'rechazado',
    compatibilidad: 45,
    modalidad: 'presencial',
  },
]

export const mockPractica: Practica = {
  id: 'prac-001',
  vacanteId: 'vac-001',
  estudianteId: 'est-001',
  empresa: 'TechCorp Colombia',
  cargo: 'Practicante Desarrollador Frontend',
  fechaInicio: '2026-02-01',
  fechaFin: '2026-07-31',
  estado: 'activa',
  calificacion: undefined,
  informesPendientes: 1,
  proximaEvaluacion: '2026-05-31',
  avancePorcentaje: 55,
}

export const mockNotificaciones: NotificacionItem[] = [
  {
    id: 'n-001',
    tipo: 'success',
    titulo: 'Entrevista confirmada',
    descripcion: 'Bancolombia confirmó tu entrevista técnica para el 14 de mayo.',
    tiempo: '2026-05-11T09:00:00',
    leida: false,
  },
  {
    id: 'n-002',
    tipo: 'warning',
    titulo: 'Informe de práctica pendiente',
    descripcion: 'Tienes un informe mensual pendiente de entrega antes del 31 de mayo.',
    tiempo: '2026-05-10T14:00:00',
    leida: false,
  },
  {
    id: 'n-003',
    tipo: 'info',
    titulo: 'Nueva vacante compatible',
    descripcion: 'Pragma publicó una vacante con 70% de compatibilidad con tu perfil.',
    tiempo: '2026-05-08T11:30:00',
    leida: true,
  },
]

// Analytics data for recharts
export const mockPostulacionesMes = [
  { mes: 'Ene', postulaciones: 3, aceptadas: 0 },
  { mes: 'Feb', postulaciones: 5, aceptadas: 1 },
  { mes: 'Mar', postulaciones: 2, aceptadas: 0 },
  { mes: 'Abr', postulaciones: 7, aceptadas: 1 },
  { mes: 'May', postulaciones: 4, aceptadas: 0 },
]

export const mockVacantesPorSector = [
  { sector: 'Tecnología', vacantes: 42 },
  { sector: 'Finanzas', vacantes: 28 },
  { sector: 'Retail', vacantes: 19 },
  { sector: 'Energía', vacantes: 11 },
  { sector: 'Fintech', vacantes: 15 },
]

export const mockKpisAdmin = [
  { label: 'Estudiantes activos', valor: '1.200' },
  { label: 'Empresas aliadas', valor: '120+' },
  { label: 'Vacantes activas', valor: '500+' },
  { label: 'Prácticas en curso', valor: '86' },
]

// Estudiantes (para vistas de empresa / admin)
export const mockEstudiantesAdmin = [
  { nombre: 'Samuel Salcedo', programa: 'Ing. Software', sem: 7, estado: 'activa', empresa: 'TechCorp Colombia' },
  { nombre: 'Laura Gómez', programa: 'Administración', sem: 8, estado: 'buscando', empresa: '—' },
  { nombre: 'Andrés Pérez', programa: 'Ing. Industrial', sem: 9, estado: 'activa', empresa: 'Bancolombia' },
  { nombre: 'Valentina Ruiz', programa: 'Diseño Gráfico', sem: 6, estado: 'buscando', empresa: '—' },
  { nombre: 'Daniel Castro', programa: 'Ing. Software', sem: 10, estado: 'finalizada', empresa: 'Pragma' },
]
